name: 'auxo'
debug: true
banner: true

global:
      mq:
        nsq:
          nsqd_addr:
          - "127.0.0.1:4150"
          max_in_flight: 5
          concurrent: 3
          max_attempt: 2
          channel_name: test.nsq
log:
  loggers:
  - level: info
    writers: json
  - name: 'auxo.net.web'
    level: debug
    writers: text
  - name: 'benchmark1'
    level: debug
    writers: drop1
  - name: 'benchmark2'
    level: debug
    writers: drop2
  writers:
  - name: drop1
    layout: '[{L}]{T}: {M}{N}'
  - name: drop2
    layout: '{level: a=b},{time: 2006-01-02T15:04:05.000Z07:00},{msg}'
    format: json
  - name: text
    type: console
    layout: '[{L}]{T}: {M} - {F:S}{N}'
    options:
      colorized: true
  - name: json
    type: console
    layout: '{level: a=b},{time: 2006-01-02T15:04:05.000Z07:00},{msg},{file: short},{text->tag: test}'
    format: json
    options:
      colorized: true

web:
  mode: develop
  entries:
  - address: :80
  - address: :443
    tls:
      key: "test.key"
      cert: "test.cert"
#      acme:
#        domain: "test.com,test.net"
#        email: ""
#        cache_dir: ""
  - address: /var/run/docker.sock
    tls:
      key: "test.key"
      cert: "test.cert"
  authorize: '*'
  read_timeout: 5s
  max_body_size: 2 M

yaml:
  name: yaml
